# Generated by Django 4.0.2 on 2022-02-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
